name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: "postgresql://johndoe:randomstring@localhost:5432/mydb?schema=public"
  NEXT_PUBLIC_VAPI_PUBLIC_KEY: "mock_public_key"
  VAPI_PUBLIC_KEY: "mock_public_key"
jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Lint
        run: npm run lint
        continue-on-error: true

      - run: npm run build
